name       : sysprof
version    : 3.42.0
release    : 5
source     :
    - https://download.gnome.org/sources/sysprof/3.42/sysprof-3.42.0.tar.xz : 3c16e03efdfe5d3e71c4d239c67741ad37f72ce8971e2f7faf168dbd5e93e886
license    : GPL-3.0-or-later
component  : system.utils
summary    : Sysprof is a statistical, system-wide profiler for Linux
description: |
    Sysprof is a sampling profiler that uses a kernel module to generate stacktraces which are then interpreted by the userspace program "sysprof". It can be used to profile almost any function in any program in terms of call percentage, battery usage, disk accesses, network usage, etc. It has special profiling support for the GTK stack. By default, Sysprof includes a CLI frontend and a GTK frontend.
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/symbol-resolver-fix-includes-for-close-lseek.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/lib64/libsysprof-capture-*.a
