name       : sysprof
version    : 3.48.0
release    : 10
source     :
    - https://download.gnome.org/sources/sysprof/3.48/sysprof-3.48.0.tar.xz : 07d9081a66cf2fb52753f48ff2b85ada75c60ff1bc1af1bd14d8aeb627972168
license    : GPL-3.0-or-later
component  : system.utils
summary    : Sysprof is a statistical, system-wide profiler for Linux
description: |
    Sysprof is a sampling profiler that uses a kernel module to generate stacktraces which are then interpreted by the userspace program "sysprof". It can be used to profile almost any function in any program in terms of call percentage, battery usage, disk accesses, network usage, etc. It has special profiling support for the GTK stack. By default, Sysprof includes a CLI frontend and a GTK frontend.
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libunwind-generic)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
