name       : sysprof
version    : 3.40.1
release    : 4
source     :
    - https://download.gnome.org/sources/sysprof/3.40/sysprof-3.40.1.tar.xz : c25000d6a20e8c4d314f5c861a1f70d7c3e2027117437fd9198fa811b9fc7437
license    : GPL-3.0-or-later
component  : system.utils
summary    : Sysprof is a statistical, system-wide profiler for Linux
description: |
    Sysprof is a sampling profiler that uses a kernel module to generate stacktraces which are then interpreted by the userspace program "sysprof". It can be used to profile almost any function in any program in terms of call percentage, battery usage, disk accesses, network usage, etc. It has special profiling support for the GTK stack. By default, Sysprof includes a CLI frontend and a GTK frontend.
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/lib64/libsysprof-capture-*.a
